# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adc_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x64\x63_driver.proto\x12\x0brpc_s32k148\x1a\x0c\x63ommon.proto\"l\n\x0c\x41\x44InitParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x12\n\nchannel_id\x18\x02 \x01(\r\x12\x0f\n\x07vref_mv\x18\x03 \x01(\r\x12\x12\n\ncounts_max\x18\x04 \x01(\r\x12\x0e\n\x06irq_id\x18\x05 \x01(\x05\"$\n\rADResetParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\"3\n\x08\x41\x44Handle\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x12\n\nchannel_id\x18\x02 \x01(\r\"G\n\x10\x41\x44GetValueReturn\x12#\n\x06status\x18\x01 \x01(\x0b\x32\x13.rpc_general.Status\x12\x0e\n\x06\x63ounts\x18\x02 \x01(\r2\xf9\x01\n\tAdcDriver\x12I\n\x15\x41\x64\x63\x44river_InitChannel\x12\x19.rpc_s32k148.ADInitParams\x1a\x13.rpc_general.Status\"\x00\x12L\n\x17\x41\x64\x63\x44river_ResetInstance\x12\x1a.rpc_s32k148.ADResetParams\x1a\x13.rpc_general.Status\"\x00\x12S\n\x19\x41\x64\x63\x44river_GetChannelValue\x12\x15.rpc_s32k148.ADHandle\x1a\x1d.rpc_s32k148.ADGetValueReturn\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adc_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADINITPARAMS']._serialized_start=47
  _globals['_ADINITPARAMS']._serialized_end=155
  _globals['_ADRESETPARAMS']._serialized_start=157
  _globals['_ADRESETPARAMS']._serialized_end=193
  _globals['_ADHANDLE']._serialized_start=195
  _globals['_ADHANDLE']._serialized_end=246
  _globals['_ADGETVALUERETURN']._serialized_start=248
  _globals['_ADGETVALUERETURN']._serialized_end=319
  _globals['_ADCDRIVER']._serialized_start=322
  _globals['_ADCDRIVER']._serialized_end=571
# @@protoc_insertion_point(module_scope)
