# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ftm_ic_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66tm_ic_driver.proto\x12\x0brpc_s32k148\x1a\x0c\x63ommon.proto\"D\n\x0f\x46tmIcInitParams\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x0e\n\x06irq_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\r\"0\n\x0b\x46tmIcHandle\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r2\xdb\x01\n\x0b\x46tmIcDriver\x12\x45\n\x0e\x46tmIc_DRV_Init\x12\x1c.rpc_s32k148.FtmIcInitParams\x1a\x13.rpc_general.Status\"\x00\x12\x42\n\x0f\x46tmIc_DRV_Start\x12\x18.rpc_s32k148.FtmIcHandle\x1a\x13.rpc_general.Status\"\x00\x12\x41\n\x0e\x46tmIc_DRV_Stop\x12\x18.rpc_s32k148.FtmIcHandle\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ftm_ic_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FTMICINITPARAMS']._serialized_start=50
  _globals['_FTMICINITPARAMS']._serialized_end=118
  _globals['_FTMICHANDLE']._serialized_start=120
  _globals['_FTMICHANDLE']._serialized_end=168
  _globals['_FTMICDRIVER']._serialized_start=171
  _globals['_FTMICDRIVER']._serialized_end=390
# @@protoc_insertion_point(module_scope)
