# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lpit_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11lpit_driver.proto\x12\x0brpc_s32k148\x1a\x0c\x63ommon.proto\"2\n\x0eLpitInitParams\x12\x10\n\x08timer_id\x18\x01 \x01(\r\x12\x0e\n\x06irq_id\x18\x02 \x01(\x05\"\x1e\n\nLpitHandle\x12\x10\n\x08timer_id\x18\x01 \x01(\r\"7\n\x13LpitSetPeriodParams\x12\x10\n\x08timer_id\x18\x01 \x01(\r\x12\x0e\n\x06period\x18\x02 \x01(\r2\xa3\x02\n\nLpitDriver\x12\x43\n\rLPIT_DRV_Init\x12\x1b.rpc_s32k148.LpitInitParams\x1a\x13.rpc_general.Status\"\x00\x12@\n\x0eLPIT_DRV_Start\x12\x17.rpc_s32k148.LpitHandle\x1a\x13.rpc_general.Status\"\x00\x12?\n\rLPIT_DRV_Stop\x12\x17.rpc_s32k148.LpitHandle\x1a\x13.rpc_general.Status\"\x00\x12M\n\x12LPIT_DRV_SetPeriod\x12 .rpc_s32k148.LpitSetPeriodParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lpit_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LPITINITPARAMS']._serialized_start=48
  _globals['_LPITINITPARAMS']._serialized_end=98
  _globals['_LPITHANDLE']._serialized_start=100
  _globals['_LPITHANDLE']._serialized_end=130
  _globals['_LPITSETPERIODPARAMS']._serialized_start=132
  _globals['_LPITSETPERIODPARAMS']._serialized_end=187
  _globals['_LPITDRIVER']._serialized_start=190
  _globals['_LPITDRIVER']._serialized_end=481
# @@protoc_insertion_point(module_scope)
