# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import pwm_driver_pb2 as pwm__driver__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pwm_driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PwmDriverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PwmDriver_InitChannel = channel.unary_unary(
                '/rpc_s32k148.PwmDriver/PwmDriver_InitChannel',
                request_serializer=pwm__driver__pb2.PDInitParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.PwmDriver_SetPeriod = channel.unary_unary(
                '/rpc_s32k148.PwmDriver/PwmDriver_SetPeriod',
                request_serializer=pwm__driver__pb2.PDSetPeriodParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.PwmDriver_SetDutyCycle = channel.unary_unary(
                '/rpc_s32k148.PwmDriver/PwmDriver_SetDutyCycle',
                request_serializer=pwm__driver__pb2.PDSetDutyCycleParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)


class PwmDriverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PwmDriver_InitChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PwmDriver_SetPeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PwmDriver_SetDutyCycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PwmDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PwmDriver_InitChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.PwmDriver_InitChannel,
                    request_deserializer=pwm__driver__pb2.PDInitParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'PwmDriver_SetPeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.PwmDriver_SetPeriod,
                    request_deserializer=pwm__driver__pb2.PDSetPeriodParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'PwmDriver_SetDutyCycle': grpc.unary_unary_rpc_method_handler(
                    servicer.PwmDriver_SetDutyCycle,
                    request_deserializer=pwm__driver__pb2.PDSetDutyCycleParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_s32k148.PwmDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_s32k148.PwmDriver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PwmDriver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PwmDriver_InitChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.PwmDriver/PwmDriver_InitChannel',
            pwm__driver__pb2.PDInitParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PwmDriver_SetPeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.PwmDriver/PwmDriver_SetPeriod',
            pwm__driver__pb2.PDSetPeriodParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PwmDriver_SetDutyCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.PwmDriver/PwmDriver_SetDutyCycle',
            pwm__driver__pb2.PDSetDutyCycleParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
