# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import rtc_driver_pb2 as rtc__driver__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rtc_driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RtcDriverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RTC_DRV_Init = channel.unary_unary(
                '/rpc_s32k148.RtcDriver/RTC_DRV_Init',
                request_serializer=rtc__driver__pb2.RtcInitParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.RTC_DRV_Enable = channel.unary_unary(
                '/rpc_s32k148.RtcDriver/RTC_DRV_Enable',
                request_serializer=rtc__driver__pb2.RtcHandle.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.RTC_DRV_Disable = channel.unary_unary(
                '/rpc_s32k148.RtcDriver/RTC_DRV_Disable',
                request_serializer=rtc__driver__pb2.RtcHandle.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.RTC_DRV_SetTimeSeconds = channel.unary_unary(
                '/rpc_s32k148.RtcDriver/RTC_DRV_SetTimeSeconds',
                request_serializer=rtc__driver__pb2.RtcSetTimeParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.RTC_DRV_ConfigureAlarm = channel.unary_unary(
                '/rpc_s32k148.RtcDriver/RTC_DRV_ConfigureAlarm',
                request_serializer=rtc__driver__pb2.RtcConfAlarmParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)


class RtcDriverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RTC_DRV_Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RTC_DRV_Enable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RTC_DRV_Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RTC_DRV_SetTimeSeconds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RTC_DRV_ConfigureAlarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RtcDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RTC_DRV_Init': grpc.unary_unary_rpc_method_handler(
                    servicer.RTC_DRV_Init,
                    request_deserializer=rtc__driver__pb2.RtcInitParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'RTC_DRV_Enable': grpc.unary_unary_rpc_method_handler(
                    servicer.RTC_DRV_Enable,
                    request_deserializer=rtc__driver__pb2.RtcHandle.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'RTC_DRV_Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.RTC_DRV_Disable,
                    request_deserializer=rtc__driver__pb2.RtcHandle.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'RTC_DRV_SetTimeSeconds': grpc.unary_unary_rpc_method_handler(
                    servicer.RTC_DRV_SetTimeSeconds,
                    request_deserializer=rtc__driver__pb2.RtcSetTimeParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'RTC_DRV_ConfigureAlarm': grpc.unary_unary_rpc_method_handler(
                    servicer.RTC_DRV_ConfigureAlarm,
                    request_deserializer=rtc__driver__pb2.RtcConfAlarmParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_s32k148.RtcDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_s32k148.RtcDriver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RtcDriver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RTC_DRV_Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.RtcDriver/RTC_DRV_Init',
            rtc__driver__pb2.RtcInitParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RTC_DRV_Enable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.RtcDriver/RTC_DRV_Enable',
            rtc__driver__pb2.RtcHandle.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RTC_DRV_Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.RtcDriver/RTC_DRV_Disable',
            rtc__driver__pb2.RtcHandle.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RTC_DRV_SetTimeSeconds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.RtcDriver/RTC_DRV_SetTimeSeconds',
            rtc__driver__pb2.RtcSetTimeParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RTC_DRV_ConfigureAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_s32k148.RtcDriver/RTC_DRV_ConfigureAlarm',
            rtc__driver__pb2.RtcConfAlarmParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
