# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtc_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rtc_driver.proto\x12\x0brpc_s32k148\x1a\x0c\x63ommon.proto\"\x1d\n\tRtcHandle\x12\x10\n\x08instance\x18\x01 \x01(\r\"I\n\rRtcInitParams\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x16\n\x0eseconds_irq_id\x18\x02 \x01(\x05\x12\x0e\n\x06irq_id\x18\x03 \x01(\x05\"5\n\x10RtcSetTimeParams\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x0f\n\x07seconds\x18\x02 \x01(\r\"\x94\x01\n\x12RtcConfAlarmParams\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x0c\n\x04time\x18\x02 \x01(\r\x12\x14\n\x0crep_interval\x18\x03 \x01(\r\x12\x16\n\x0enumber_of_reps\x18\x04 \x01(\r\x12\x16\n\x0erepeat_forever\x18\x05 \x01(\x08\x12\x18\n\x10\x61larm_int_enable\x18\x06 \x01(\x08\x32\xf3\x02\n\tRtcDriver\x12\x41\n\x0cRTC_DRV_Init\x12\x1a.rpc_s32k148.RtcInitParams\x1a\x13.rpc_general.Status\"\x00\x12?\n\x0eRTC_DRV_Enable\x12\x16.rpc_s32k148.RtcHandle\x1a\x13.rpc_general.Status\"\x00\x12@\n\x0fRTC_DRV_Disable\x12\x16.rpc_s32k148.RtcHandle\x1a\x13.rpc_general.Status\"\x00\x12N\n\x16RTC_DRV_SetTimeSeconds\x12\x1d.rpc_s32k148.RtcSetTimeParams\x1a\x13.rpc_general.Status\"\x00\x12P\n\x16RTC_DRV_ConfigureAlarm\x12\x1f.rpc_s32k148.RtcConfAlarmParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtc_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RTCHANDLE']._serialized_start=47
  _globals['_RTCHANDLE']._serialized_end=76
  _globals['_RTCINITPARAMS']._serialized_start=78
  _globals['_RTCINITPARAMS']._serialized_end=151
  _globals['_RTCSETTIMEPARAMS']._serialized_start=153
  _globals['_RTCSETTIMEPARAMS']._serialized_end=206
  _globals['_RTCCONFALARMPARAMS']._serialized_start=209
  _globals['_RTCCONFALARMPARAMS']._serialized_end=357
  _globals['_RTCDRIVER']._serialized_start=360
  _globals['_RTCDRIVER']._serialized_end=731
# @@protoc_insertion_point(module_scope)
