# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: s32k148_sif_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18s32k148_sif_driver.proto\x12\x0brpc_s32k148\x1a\x0c\x63ommon.proto\"1\n\rSifInitParams\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x0e\n\x06irq_id\x18\x02 \x01(\x05\"X\n\rSifReadParams\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x11\n\tperiph_id\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\r\x12\x14\n\x0cirq_required\x18\x04 \x01(\x08\"\\\n\x0eSifWriteParams\x12\x10\n\x08instance\x18\x01 \x01(\r\x12\x11\n\tperiph_id\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\x0c\x12\x14\n\x0cirq_required\x18\x04 \x01(\x08\"F\n\x0eSifReadReturns\x12#\n\x06status\x18\x01 \x01(\x0b\x32\x13.rpc_general.Status\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x32\xde\x01\n\tSifDriver\x12\x41\n\x0cSIF_DRV_Init\x12\x1a.rpc_s32k148.SifInitParams\x1a\x13.rpc_general.Status\"\x00\x12\x43\n\rSIF_DRV_Write\x12\x1b.rpc_s32k148.SifWriteParams\x1a\x13.rpc_general.Status\"\x00\x12I\n\x0cSIF_DRV_Read\x12\x1a.rpc_s32k148.SifReadParams\x1a\x1b.rpc_s32k148.SifReadReturns\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 's32k148_sif_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIFINITPARAMS']._serialized_start=55
  _globals['_SIFINITPARAMS']._serialized_end=104
  _globals['_SIFREADPARAMS']._serialized_start=106
  _globals['_SIFREADPARAMS']._serialized_end=194
  _globals['_SIFWRITEPARAMS']._serialized_start=196
  _globals['_SIFWRITEPARAMS']._serialized_end=288
  _globals['_SIFREADRETURNS']._serialized_start=290
  _globals['_SIFREADRETURNS']._serialized_end=360
  _globals['_SIFDRIVER']._serialized_start=363
  _globals['_SIFDRIVER']._serialized_end=585
# @@protoc_insertion_point(module_scope)
