# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import async_interface_pb2 as async__interface__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in async_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AsyncInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AsyncInterface_Init = channel.unary_unary(
                '/rpc_general.AsyncInterface/AsyncInterface_Init',
                request_serializer=async__interface__pb2.AIInitParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.AsyncInterface_Enable = channel.unary_unary(
                '/rpc_general.AsyncInterface/AsyncInterface_Enable',
                request_serializer=async__interface__pb2.AIInterfaceId.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.AsyncInterface_Disable = channel.unary_unary(
                '/rpc_general.AsyncInterface/AsyncInterface_Disable',
                request_serializer=async__interface__pb2.AIInterfaceId.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.AsyncInterface_ReadReq = channel.unary_unary(
                '/rpc_general.AsyncInterface/AsyncInterface_ReadReq',
                request_serializer=async__interface__pb2.AIReadReqParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.AsyncInterface_GetReadData = channel.unary_unary(
                '/rpc_general.AsyncInterface/AsyncInterface_GetReadData',
                request_serializer=async__interface__pb2.AIInterfaceId.SerializeToString,
                response_deserializer=async__interface__pb2.AIGetReadDataReturn.FromString,
                _registered_method=True)
        self.AsyncInterface_WriteReq = channel.unary_unary(
                '/rpc_general.AsyncInterface/AsyncInterface_WriteReq',
                request_serializer=async__interface__pb2.AIWriteReqParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)


class AsyncInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AsyncInterface_Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncInterface_Enable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncInterface_Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncInterface_ReadReq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncInterface_GetReadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncInterface_WriteReq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AsyncInterface_Init': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncInterface_Init,
                    request_deserializer=async__interface__pb2.AIInitParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'AsyncInterface_Enable': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncInterface_Enable,
                    request_deserializer=async__interface__pb2.AIInterfaceId.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'AsyncInterface_Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncInterface_Disable,
                    request_deserializer=async__interface__pb2.AIInterfaceId.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'AsyncInterface_ReadReq': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncInterface_ReadReq,
                    request_deserializer=async__interface__pb2.AIReadReqParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'AsyncInterface_GetReadData': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncInterface_GetReadData,
                    request_deserializer=async__interface__pb2.AIInterfaceId.FromString,
                    response_serializer=async__interface__pb2.AIGetReadDataReturn.SerializeToString,
            ),
            'AsyncInterface_WriteReq': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncInterface_WriteReq,
                    request_deserializer=async__interface__pb2.AIWriteReqParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_general.AsyncInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_general.AsyncInterface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsyncInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AsyncInterface_Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.AsyncInterface/AsyncInterface_Init',
            async__interface__pb2.AIInitParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncInterface_Enable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.AsyncInterface/AsyncInterface_Enable',
            async__interface__pb2.AIInterfaceId.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncInterface_Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.AsyncInterface/AsyncInterface_Disable',
            async__interface__pb2.AIInterfaceId.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncInterface_ReadReq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.AsyncInterface/AsyncInterface_ReadReq',
            async__interface__pb2.AIReadReqParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncInterface_GetReadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.AsyncInterface/AsyncInterface_GetReadData',
            async__interface__pb2.AIInterfaceId.SerializeToString,
            async__interface__pb2.AIGetReadDataReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncInterface_WriteReq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.AsyncInterface/AsyncInterface_WriteReq',
            async__interface__pb2.AIWriteReqParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
