# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async_interface.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61sync_interface.proto\x12\x0brpc_general\x1a\x0c\x63ommon.proto\"4\n\x0c\x41IInitParams\x12\x14\n\x0cinterface_id\x18\x01 \x01(\r\x12\x0e\n\x06irq_id\x18\x02 \x01(\x05\"%\n\rAIInterfaceId\x12\x14\n\x0cinterface_id\x18\x01 \x01(\r\":\n\x0f\x41IReadReqParams\x12\x14\n\x0cinterface_id\x18\x01 \x01(\r\x12\x11\n\tdata_size\x18\x02 \x01(\r\"N\n\x13\x41IGetReadDataReturn\x12#\n\x06status\x18\x01 \x01(\x0b\x32\x13.rpc_general.Status\x12\x12\n\ndata_bytes\x18\x02 \x01(\x0c\"<\n\x10\x41IWriteReqParams\x12\x14\n\x0cinterface_id\x18\x01 \x01(\r\x12\x12\n\ndata_bytes\x18\x02 \x01(\x0c*\x8d\x01\n\nAIIrqFlags\x12\x16\n\x12\x41IIrqFlags_RX_FULL\x10\x00\x12\x17\n\x13\x41IIrqFlags_TX_EMPTY\x10\x01\x12\x1b\n\x17\x41IIrqFlags_END_TRANSFER\x10\x02\x12\x14\n\x10\x41IIrqFlags_ERROR\x10\x03\x12\x1b\n\x17\x41IIrqFlags_RX_IDLE_LINE\x10\x04\x32\xf0\x03\n\x0e\x41syncInterface\x12G\n\x13\x41syncInterface_Init\x12\x19.rpc_general.AIInitParams\x1a\x13.rpc_general.Status\"\x00\x12J\n\x15\x41syncInterface_Enable\x12\x1a.rpc_general.AIInterfaceId\x1a\x13.rpc_general.Status\"\x00\x12K\n\x16\x41syncInterface_Disable\x12\x1a.rpc_general.AIInterfaceId\x1a\x13.rpc_general.Status\"\x00\x12M\n\x16\x41syncInterface_ReadReq\x12\x1c.rpc_general.AIReadReqParams\x1a\x13.rpc_general.Status\"\x00\x12\\\n\x1a\x41syncInterface_GetReadData\x12\x1a.rpc_general.AIInterfaceId\x1a .rpc_general.AIGetReadDataReturn\"\x00\x12O\n\x17\x41syncInterface_WriteReq\x12\x1d.rpc_general.AIWriteReqParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'async_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIIRQFLAGS']._serialized_start=348
  _globals['_AIIRQFLAGS']._serialized_end=489
  _globals['_AIINITPARAMS']._serialized_start=52
  _globals['_AIINITPARAMS']._serialized_end=104
  _globals['_AIINTERFACEID']._serialized_start=106
  _globals['_AIINTERFACEID']._serialized_end=143
  _globals['_AIREADREQPARAMS']._serialized_start=145
  _globals['_AIREADREQPARAMS']._serialized_end=203
  _globals['_AIGETREADDATARETURN']._serialized_start=205
  _globals['_AIGETREADDATARETURN']._serialized_end=283
  _globals['_AIWRITEREQPARAMS']._serialized_start=285
  _globals['_AIWRITEREQPARAMS']._serialized_end=345
  _globals['_ASYNCINTERFACE']._serialized_start=492
  _globals['_ASYNCINTERFACE']._serialized_end=988
# @@protoc_insertion_point(module_scope)
