# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconnect.proto\x12\x0brpc_general\x1a\x0c\x63ommon.proto\"#\n\x10HandShakeRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eHandShakeReply\x12\x0f\n\x07message\x18\x01 \x01(\t\";\n\x0c\x43loseRequest\x12+\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1d.rpc_general.CloseRequestEnum\"1\n\nCloseReply\x12#\n\x06status\x18\x01 \x01(\x0b\x32\x13.rpc_general.Status*M\n\x10\x43loseRequestEnum\x12\x17\n\x13\x46SW_CLOSE_REQ_RESET\x10\x00\x12 \n\x1c\x46SW_CLOSE_REQ_CRITICAL_ERROR\x10\x01\x32\x93\x01\n\x07\x43onnect\x12I\n\tHandShake\x12\x1d.rpc_general.HandShakeRequest\x1a\x1b.rpc_general.HandShakeReply\"\x00\x12=\n\x05\x43lose\x12\x19.rpc_general.CloseRequest\x1a\x17.rpc_general.CloseReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOSEREQUESTENUM']._serialized_start=228
  _globals['_CLOSEREQUESTENUM']._serialized_end=305
  _globals['_HANDSHAKEREQUEST']._serialized_start=44
  _globals['_HANDSHAKEREQUEST']._serialized_end=79
  _globals['_HANDSHAKEREPLY']._serialized_start=81
  _globals['_HANDSHAKEREPLY']._serialized_end=114
  _globals['_CLOSEREQUEST']._serialized_start=116
  _globals['_CLOSEREQUEST']._serialized_end=175
  _globals['_CLOSEREPLY']._serialized_start=177
  _globals['_CLOSEREPLY']._serialized_end=226
  _globals['_CONNECT']._serialized_start=308
  _globals['_CONNECT']._serialized_end=455
# @@protoc_insertion_point(module_scope)
