# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import flexcan_driver_pb2 as flexcan__driver__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in flexcan_driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FlexCanDriverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FLEXCAN_DRV_Init = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_Init',
                request_serializer=flexcan__driver__pb2.FCInitParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.FLEXCAN_DRV_EnterFreezeMode = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_EnterFreezeMode',
                request_serializer=flexcan__driver__pb2.FCFreezeModeParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.FLEXCAN_DRV_ExitFreezeMode = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_ExitFreezeMode',
                request_serializer=flexcan__driver__pb2.FCFreezeModeParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.FLEXCAN_DRV_Send = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_Send',
                request_serializer=flexcan__driver__pb2.FCSendParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.FLEXCAN_DRV_SetRxIndividualMask = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_SetRxIndividualMask',
                request_serializer=flexcan__driver__pb2.FCSetRxIndMaskParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.FLEXCAN_DRV_ConfigRxMb = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_ConfigRxMb',
                request_serializer=flexcan__driver__pb2.FCConfigRxMbParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.FLEXCAN_DRV_ReceiveReq = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_ReceiveReq',
                request_serializer=flexcan__driver__pb2.FCReceiveReqParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.FLEXCAN_DRV_GetReceivedData = channel.unary_unary(
                '/rpc_general.FlexCanDriver/FLEXCAN_DRV_GetReceivedData',
                request_serializer=flexcan__driver__pb2.FCGetReceivedDataParams.SerializeToString,
                response_deserializer=flexcan__driver__pb2.FCGetReceivedDataReturn.FromString,
                _registered_method=True)


class FlexCanDriverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FLEXCAN_DRV_Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FLEXCAN_DRV_EnterFreezeMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FLEXCAN_DRV_ExitFreezeMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FLEXCAN_DRV_Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FLEXCAN_DRV_SetRxIndividualMask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FLEXCAN_DRV_ConfigRxMb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FLEXCAN_DRV_ReceiveReq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FLEXCAN_DRV_GetReceivedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlexCanDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FLEXCAN_DRV_Init': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_Init,
                    request_deserializer=flexcan__driver__pb2.FCInitParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'FLEXCAN_DRV_EnterFreezeMode': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_EnterFreezeMode,
                    request_deserializer=flexcan__driver__pb2.FCFreezeModeParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'FLEXCAN_DRV_ExitFreezeMode': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_ExitFreezeMode,
                    request_deserializer=flexcan__driver__pb2.FCFreezeModeParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'FLEXCAN_DRV_Send': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_Send,
                    request_deserializer=flexcan__driver__pb2.FCSendParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'FLEXCAN_DRV_SetRxIndividualMask': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_SetRxIndividualMask,
                    request_deserializer=flexcan__driver__pb2.FCSetRxIndMaskParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'FLEXCAN_DRV_ConfigRxMb': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_ConfigRxMb,
                    request_deserializer=flexcan__driver__pb2.FCConfigRxMbParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'FLEXCAN_DRV_ReceiveReq': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_ReceiveReq,
                    request_deserializer=flexcan__driver__pb2.FCReceiveReqParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'FLEXCAN_DRV_GetReceivedData': grpc.unary_unary_rpc_method_handler(
                    servicer.FLEXCAN_DRV_GetReceivedData,
                    request_deserializer=flexcan__driver__pb2.FCGetReceivedDataParams.FromString,
                    response_serializer=flexcan__driver__pb2.FCGetReceivedDataReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_general.FlexCanDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_general.FlexCanDriver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlexCanDriver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FLEXCAN_DRV_Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_Init',
            flexcan__driver__pb2.FCInitParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FLEXCAN_DRV_EnterFreezeMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_EnterFreezeMode',
            flexcan__driver__pb2.FCFreezeModeParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FLEXCAN_DRV_ExitFreezeMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_ExitFreezeMode',
            flexcan__driver__pb2.FCFreezeModeParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FLEXCAN_DRV_Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_Send',
            flexcan__driver__pb2.FCSendParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FLEXCAN_DRV_SetRxIndividualMask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_SetRxIndividualMask',
            flexcan__driver__pb2.FCSetRxIndMaskParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FLEXCAN_DRV_ConfigRxMb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_ConfigRxMb',
            flexcan__driver__pb2.FCConfigRxMbParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FLEXCAN_DRV_ReceiveReq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_ReceiveReq',
            flexcan__driver__pb2.FCReceiveReqParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FLEXCAN_DRV_GetReceivedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_general.FlexCanDriver/FLEXCAN_DRV_GetReceivedData',
            flexcan__driver__pb2.FCGetReceivedDataParams.SerializeToString,
            flexcan__driver__pb2.FCGetReceivedDataReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
