# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interrupts.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10interrupts.proto\x12\x0brpc_general\x1a\x0c\x63ommon.proto\"\"\n\x0bIdleContext\x12\x13\n\x0bidle_cycles\x18\x01 \x01(\r\"C\n\x10InterruptContext\x12\x0e\n\x06irq_id\x18\x01 \x01(\x05\x12\x11\n\tirq_flags\x18\x02 \x01(\r\x12\x0c\n\x04time\x18\x03 \x01(\x04\"E\n\x15InterruptContextQueue\x12,\n\x05queue\x18\x01 \x03(\x0b\x32\x1d.rpc_general.InterruptContext2`\n\nInterrupts\x12R\n\x10WaitForInterrupt\x12\x18.rpc_general.IdleContext\x1a\".rpc_general.InterruptContextQueue\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interrupts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDLECONTEXT']._serialized_start=47
  _globals['_IDLECONTEXT']._serialized_end=81
  _globals['_INTERRUPTCONTEXT']._serialized_start=83
  _globals['_INTERRUPTCONTEXT']._serialized_end=150
  _globals['_INTERRUPTCONTEXTQUEUE']._serialized_start=152
  _globals['_INTERRUPTCONTEXTQUEUE']._serialized_end=221
  _globals['_INTERRUPTS']._serialized_start=223
  _globals['_INTERRUPTS']._serialized_end=319
# @@protoc_insertion_point(module_scope)
