# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emios_qdec_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import emios_common_pb2 as emios__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65mios_qdec_driver.proto\x12\x0crpc_mpc5777c\x1a\x0c\x63ommon.proto\x1a\x12\x65mios_common.proto\"\xbd\x02\n\x0f\x45miosQdecParams\x12\x13\n\x0b\x65mios_group\x18\x01 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12)\n\x04mode\x18\x03 \x01(\x0e\x32\x1b.rpc_mpc5777c.EmiosQdecMode\x12\x38\n\x0c\x66ilter_input\x18\x04 \x01(\x0e\x32\".rpc_mpc5777c.EmiosInputFilterType\x12\x11\n\tfilter_en\x18\x05 \x01(\x08\x12;\n\rchan_polarity\x18\x06 \x01(\x0e\x32$.rpc_mpc5777c.EmiosPulsePolarityType\x12?\n\x11\x61ux_chan_polarity\x18\x07 \x01(\x0e\x32$.rpc_mpc5777c.EmiosPulsePolarityType\x12\x0e\n\x06irq_id\x18\x08 \x01(\x05\"M\n\x15\x45miosQdecTargetParams\x12\x13\n\x0b\x65mios_group\x18\x01 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12\x0e\n\x06target\x18\x03 \x01(\r*]\n\rEmiosQdecMode\x12\x16\n\x12\x45miosQdecMode_ZERO\x10\x00\x12\x1b\n\x17\x45miosQdecMode_DIRECTION\x10\x0c\x12\x17\n\x13\x45miosQdecMode_PHASE\x10\r*b\n\x16\x45miosPulsePolarityType\x12#\n\x1f\x45miosPulsePolarityType_NEGATIVE\x10\x00\x12#\n\x1f\x45miosPulsePolarityType_POSITIVE\x10\x01\x32\xc0\x01\n\x0f\x45miosQdecDriver\x12U\n\x1d\x45MIOS_DRV_QDEC_Init_and_Reset\x12\x1d.rpc_mpc5777c.EmiosQdecParams\x1a\x13.rpc_general.Status\"\x00\x12V\n\x18\x45MIOS_DRV_QDEC_SetTarget\x12#.rpc_mpc5777c.EmiosQdecTargetParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emios_qdec_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMIOSQDECMODE']._serialized_start=474
  _globals['_EMIOSQDECMODE']._serialized_end=567
  _globals['_EMIOSPULSEPOLARITYTYPE']._serialized_start=569
  _globals['_EMIOSPULSEPOLARITYTYPE']._serialized_end=667
  _globals['_EMIOSQDECPARAMS']._serialized_start=76
  _globals['_EMIOSQDECPARAMS']._serialized_end=393
  _globals['_EMIOSQDECTARGETPARAMS']._serialized_start=395
  _globals['_EMIOSQDECTARGETPARAMS']._serialized_end=472
  _globals['_EMIOSQDECDRIVER']._serialized_start=670
  _globals['_EMIOSQDECDRIVER']._serialized_end=862
# @@protoc_insertion_point(module_scope)
