# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import emios_common_pb2 as emios__common__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in emios_common_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EmiosCommonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EMIOS_DRV_InitGlobal = channel.unary_unary(
                '/rpc_mpc5777c.EmiosCommon/EMIOS_DRV_InitGlobal',
                request_serializer=emios__common__pb2.EmiosInitGlobalParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.EMIOS_DRV_SetPrescalerEnableBit = channel.unary_unary(
                '/rpc_mpc5777c.EmiosCommon/EMIOS_DRV_SetPrescalerEnableBit',
                request_serializer=emios__common__pb2.EmiosSetPrescalerEnParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)


class EmiosCommonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EMIOS_DRV_InitGlobal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EMIOS_DRV_SetPrescalerEnableBit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmiosCommonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EMIOS_DRV_InitGlobal': grpc.unary_unary_rpc_method_handler(
                    servicer.EMIOS_DRV_InitGlobal,
                    request_deserializer=emios__common__pb2.EmiosInitGlobalParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'EMIOS_DRV_SetPrescalerEnableBit': grpc.unary_unary_rpc_method_handler(
                    servicer.EMIOS_DRV_SetPrescalerEnableBit,
                    request_deserializer=emios__common__pb2.EmiosSetPrescalerEnParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_mpc5777c.EmiosCommon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_mpc5777c.EmiosCommon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmiosCommon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EMIOS_DRV_InitGlobal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_mpc5777c.EmiosCommon/EMIOS_DRV_InitGlobal',
            emios__common__pb2.EmiosInitGlobalParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EMIOS_DRV_SetPrescalerEnableBit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_mpc5777c.EmiosCommon/EMIOS_DRV_SetPrescalerEnableBit',
            emios__common__pb2.EmiosSetPrescalerEnParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
