# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emios_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65mios_common.proto\x12\x0crpc_mpc5777c\x1a\x0c\x63ommon.proto\"\x82\x02\n\x15\x45miosInitGlobalParams\x12\x13\n\x0b\x65mios_group\x18\x01 \x01(\r\x12\x18\n\x10\x61llow_debug_mode\x18\x02 \x01(\x08\x12\x16\n\x0elow_power_mode\x18\x03 \x01(\x08\x12\x13\n\x0b\x63lk_div_val\x18\x04 \x01(\r\x12\x1f\n\x17\x65nable_global_prescaler\x18\x05 \x01(\x08\x12\x1f\n\x17\x65nable_global_time_base\x18\x06 \x01(\x08\x12!\n\x19\x65nable_external_time_base\x18\x07 \x01(\x08\x12\x18\n\x10server_time_slot\x18\x08 \x01(\r\x12\x0e\n\x06irq_id\x18\t \x01(\x05\"P\n\x19\x45miosSetPrescalerEnParams\x12\x13\n\x0b\x65mios_group\x18\x01 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\x08*\xa1\x01\n\x14\x45miosInputFilterType\x12\x1d\n\x19\x45MIOS_INPUT_FILTER_BYPASS\x10\x00\x12\x19\n\x15\x45MIOS_INPUT_FILTER_02\x10\x01\x12\x19\n\x15\x45MIOS_INPUT_FILTER_04\x10\x02\x12\x19\n\x15\x45MIOS_INPUT_FILTER_08\x10\x04\x12\x19\n\x15\x45MIOS_INPUT_FILTER_16\x10\x08\x32\xc4\x01\n\x0b\x45miosCommon\x12R\n\x14\x45MIOS_DRV_InitGlobal\x12#.rpc_mpc5777c.EmiosInitGlobalParams\x1a\x13.rpc_general.Status\"\x00\x12\x61\n\x1f\x45MIOS_DRV_SetPrescalerEnableBit\x12\'.rpc_mpc5777c.EmiosSetPrescalerEnParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emios_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMIOSINPUTFILTERTYPE']._serialized_start=394
  _globals['_EMIOSINPUTFILTERTYPE']._serialized_end=555
  _globals['_EMIOSINITGLOBALPARAMS']._serialized_start=51
  _globals['_EMIOSINITGLOBALPARAMS']._serialized_end=309
  _globals['_EMIOSSETPRESCALERENPARAMS']._serialized_start=311
  _globals['_EMIOSSETPRESCALERENPARAMS']._serialized_end=391
  _globals['_EMIOSCOMMON']._serialized_start=558
  _globals['_EMIOSCOMMON']._serialized_end=754
# @@protoc_insertion_point(module_scope)
