# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import mpc5777c_sif_driver_pb2 as mpc5777c__sif__driver__pb2
from framework.hardware_interfaces.drivers import BaseSifDriver

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mpc5777c_sif_driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SifDriverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SIF_DRV_Init = channel.unary_unary(
                '/rpc_mpc5777c.SifDriver/SIF_DRV_Init',
                request_serializer=mpc5777c__sif__driver__pb2.SifInitParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.SIF_DRV_Write = channel.unary_unary(
                '/rpc_mpc5777c.SifDriver/SIF_DRV_Write',
                request_serializer=mpc5777c__sif__driver__pb2.SifWriteParams.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                _registered_method=True)
        self.SIF_DRV_Read = channel.unary_unary(
                '/rpc_mpc5777c.SifDriver/SIF_DRV_Read',
                request_serializer=mpc5777c__sif__driver__pb2.SifReadParams.SerializeToString,
                response_deserializer=mpc5777c__sif__driver__pb2.SifReadReturns.FromString,
                _registered_method=True)


class SifDriverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SIF_DRV_Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SIF_DRV_Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SIF_DRV_Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SifDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SIF_DRV_Init': grpc.unary_unary_rpc_method_handler(
                    servicer.SIF_DRV_Init,
                    request_deserializer=mpc5777c__sif__driver__pb2.SifInitParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'SIF_DRV_Write': grpc.unary_unary_rpc_method_handler(
                    servicer.SIF_DRV_Write,
                    request_deserializer=mpc5777c__sif__driver__pb2.SifWriteParams.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'SIF_DRV_Read': grpc.unary_unary_rpc_method_handler(
                    servicer.SIF_DRV_Read,
                    request_deserializer=mpc5777c__sif__driver__pb2.SifReadParams.FromString,
                    response_serializer=mpc5777c__sif__driver__pb2.SifReadReturns.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_mpc5777c.SifDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_mpc5777c.SifDriver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SifDriver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SIF_DRV_Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_mpc5777c.SifDriver/SIF_DRV_Init',
            mpc5777c__sif__driver__pb2.SifInitParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SIF_DRV_Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_mpc5777c.SifDriver/SIF_DRV_Write',
            mpc5777c__sif__driver__pb2.SifWriteParams.SerializeToString,
            common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SIF_DRV_Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_mpc5777c.SifDriver/SIF_DRV_Read',
            mpc5777c__sif__driver__pb2.SifReadParams.SerializeToString,
            mpc5777c__sif__driver__pb2.SifReadReturns.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
