# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpc5777c_eqadc_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmpc5777c_eqadc_driver.proto\x12\x0crpc_mpc5777c\x1a\x0c\x63ommon.proto\"N\n\x0b\x45qAdcConfig\x12\x0e\n\x06\x61\x64\x63_id\x18\x01 \x01(\r\x12\x11\n\tprescaler\x18\x02 \x01(\r\x12\x0c\n\x04gain\x18\x03 \x01(\r\x12\x0e\n\x06offset\x18\x04 \x01(\r\"s\n\x0c\x45qAdcCommand\x12\x12\n\nchannel_id\x18\x01 \x01(\r\x12\x15\n\rsampling_time\x18\x02 \x01(\r\x12\x14\n\x0c\x65nable_calib\x18\x03 \x01(\x08\x12\x13\n\x0b\x65nable_sign\x18\x04 \x01(\x08\x12\r\n\x05pause\x18\x05 \x01(\x08\"\xac\x01\n\x0f\x45qAdcInitParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x13\n\x0bsamples_num\x18\x02 \x01(\r\x12-\n\nadc_config\x18\x03 \x03(\x0b\x32\x19.rpc_mpc5777c.EqAdcConfig\x12\x30\n\x0c\x61\x64\x63_commands\x18\x04 \x03(\x0b\x32\x1a.rpc_mpc5777c.EqAdcCommand\x12\x0e\n\x06irq_id\x18\x05 \x01(\x05\"T\n\x1f\x45qAdcCcCalibrateConverterParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x0c\n\x04gain\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"F\n\x1b\x45qAdcCCSamplesRequestParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x12\n\nchannel_id\x18\x02 \x03(\x05\x32\xa2\x02\n\x0b\x45qAdcDriver\x12I\n\x11\x45QADC_DRV_CC_Init\x12\x1d.rpc_mpc5777c.EqAdcInitParams\x1a\x13.rpc_general.Status\"\x00\x12g\n\x1f\x45QADC_DRV_CC_CalibrateConverter\x12-.rpc_mpc5777c.EqAdcCcCalibrateConverterParams\x1a\x13.rpc_general.Status\"\x00\x12_\n\x1b\x45QADC_DRV_CC_SamplesRequest\x12).rpc_mpc5777c.EqAdcCCSamplesRequestParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mpc5777c_eqadc_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EQADCCONFIG']._serialized_start=59
  _globals['_EQADCCONFIG']._serialized_end=137
  _globals['_EQADCCOMMAND']._serialized_start=139
  _globals['_EQADCCOMMAND']._serialized_end=254
  _globals['_EQADCINITPARAMS']._serialized_start=257
  _globals['_EQADCINITPARAMS']._serialized_end=429
  _globals['_EQADCCCCALIBRATECONVERTERPARAMS']._serialized_start=431
  _globals['_EQADCCCCALIBRATECONVERTERPARAMS']._serialized_end=515
  _globals['_EQADCCCSAMPLESREQUESTPARAMS']._serialized_start=517
  _globals['_EQADCCCSAMPLESREQUESTPARAMS']._serialized_end=587
  _globals['_EQADCDRIVER']._serialized_start=590
  _globals['_EQADCDRIVER']._serialized_end=880
# @@protoc_insertion_point(module_scope)
