# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpc5777c_pins_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ampc5777c_pins_driver.proto\x12\x0crpc_mpc5777c\x1a\x0c\x63ommon.proto\"x\n\x10PinSettingConfig\x12\x0e\n\x06pin_id\x18\x01 \x01(\r\x12\x12\n\ninit_value\x18\x02 \x01(\r\x12\x0b\n\x03mux\x18\x03 \x01(\r\x12\x19\n\x11output_mux_enable\x18\x04 \x01(\x08\x12\x18\n\x10input_mux_enable\x18\x05 \x01(\x08\">\n\x0f\x43onfigMuxParams\x12\x0e\n\x06pin_id\x18\x01 \x01(\r\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x12\x0b\n\x03mux\x18\x03 \x01(\r\"\x1f\n\rPinReadParams\x12\x0e\n\x06pin_id\x18\x01 \x01(\r\"/\n\x0ePinWriteParams\x12\x0e\n\x06pin_id\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r\"P\n\x0ePinsInitParams\x12\x0e\n\x06irq_id\x18\x01 \x01(\x05\x12.\n\x06\x63onfig\x18\x02 \x03(\x0b\x32\x1e.rpc_mpc5777c.PinSettingConfig\"C\n\rPinReadReturn\x12#\n\x06status\x18\x01 \x01(\x0b\x32\x13.rpc_general.Status\x12\r\n\x05value\x18\x02 \x01(\r2\xa3\x03\n\nPinsDriver\x12\x44\n\rPINS_DRV_Init\x12\x1c.rpc_mpc5777c.PinsInitParams\x1a\x13.rpc_general.Status\"\x00\x12S\n\x15PINS_DRV_QuickReadPin\x12\x1b.rpc_mpc5777c.PinReadParams\x1a\x1b.rpc_mpc5777c.PinReadReturn\"\x00\x12M\n\x16PINS_DRV_QuickWritePin\x12\x1c.rpc_mpc5777c.PinWriteParams\x1a\x13.rpc_general.Status\"\x00\x12U\n\x1dPINS_DRV_QuickConfigOutputMux\x12\x1d.rpc_mpc5777c.ConfigMuxParams\x1a\x13.rpc_general.Status\"\x00\x12T\n\x1cPINS_DRV_QuickConfigInputMux\x12\x1d.rpc_mpc5777c.ConfigMuxParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mpc5777c_pins_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINSETTINGCONFIG']._serialized_start=58
  _globals['_PINSETTINGCONFIG']._serialized_end=178
  _globals['_CONFIGMUXPARAMS']._serialized_start=180
  _globals['_CONFIGMUXPARAMS']._serialized_end=242
  _globals['_PINREADPARAMS']._serialized_start=244
  _globals['_PINREADPARAMS']._serialized_end=275
  _globals['_PINWRITEPARAMS']._serialized_start=277
  _globals['_PINWRITEPARAMS']._serialized_end=324
  _globals['_PINSINITPARAMS']._serialized_start=326
  _globals['_PINSINITPARAMS']._serialized_end=406
  _globals['_PINREADRETURN']._serialized_start=408
  _globals['_PINREADRETURN']._serialized_end=475
  _globals['_PINSDRIVER']._serialized_start=478
  _globals['_PINSDRIVER']._serialized_end=897
# @@protoc_insertion_point(module_scope)
