# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pit_driver.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pit_driver.proto\x12\x0crpc_mpc5777c\x1a\x0c\x63ommon.proto\";\n\x10PitChannelParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x12\n\nchannel_id\x18\x02 \x01(\r\"N\n\x13PitChannelIrqParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x12\n\nchannel_id\x18\x02 \x01(\r\x12\x0e\n\x06irq_id\x18\x03 \x01(\r\"T\n\x16PitSetPeriodByUsParams\x12\x13\n\x0binstance_id\x18\x01 \x01(\r\x12\x12\n\nchannel_id\x18\x02 \x01(\r\x12\x11\n\tperiod_us\x18\x03 \x01(\r2\xa9\x03\n\tPitDriver\x12M\n\x14PIT_DRV_StartChannel\x12\x1e.rpc_mpc5777c.PitChannelParams\x1a\x13.rpc_general.Status\"\x00\x12L\n\x13PIT_DRV_StopChannel\x12\x1e.rpc_mpc5777c.PitChannelParams\x1a\x13.rpc_general.Status\"\x00\x12T\n\x15PIT_DRV_SetPeriodByUs\x12$.rpc_mpc5777c.PitSetPeriodByUsParams\x1a\x13.rpc_general.Status\"\x00\x12S\n\x17PIT_DRV_EnableInterrupt\x12!.rpc_mpc5777c.PitChannelIrqParams\x1a\x13.rpc_general.Status\"\x00\x12T\n\x18PIT_DRV_DisableInterrupt\x12!.rpc_mpc5777c.PitChannelIrqParams\x1a\x13.rpc_general.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pit_driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PITCHANNELPARAMS']._serialized_start=48
  _globals['_PITCHANNELPARAMS']._serialized_end=107
  _globals['_PITCHANNELIRQPARAMS']._serialized_start=109
  _globals['_PITCHANNELIRQPARAMS']._serialized_end=187
  _globals['_PITSETPERIODBYUSPARAMS']._serialized_start=189
  _globals['_PITSETPERIODBYUSPARAMS']._serialized_end=273
  _globals['_PITDRIVER']._serialized_start=276
  _globals['_PITDRIVER']._serialized_end=701
# @@protoc_insertion_point(module_scope)
